#!/usr/bin/sh

# Uses dmenu to search for a PDF file within a directory, then open it with mupdf.

PAPERSDIR="$HOME/Papers"

mupdf "$(find "$PAPERSDIR" -iname "*.pdf" | sort | dmenu -b -i -p "Buscar paper:" -l 10 -nb "#2E2E2E" -nf "#FDF6E3" -sb "#D5807D" -sf "#FDF6E3")"
